# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltMDXmBIbTEGckxUMsaPFuFoJa0D9LT5
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/add', methods=['POST'])
def add_numbers():
    # Get JSON input from the request
    data = request.get_json()
    if not data or 'num1' not in data or 'num2' not in data:
        return jsonify({'error': 'Please provide both "num1" and "num2" in the JSON payload.'}), 400

    try:
        # Extract numbers from the input
        num1 = float(data['num1'])
        num2 = float(data['num2'])

        # Compute the sum
        result = num1 + num2

        # Return the result as JSON
        return jsonify({'num1': num1, 'num2': num2, 'sum': result})

    except ValueError:
        return jsonify({'error': 'Both inputs must be numbers.'}), 400

if __name__ == '__main__':
    app.run(debug=True)